<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Encore un Blog ?! #nonMaisAllo</title>

    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/blog-main.css">
    <link rel="stylesheet" href="css/blog-theme.css">
    <link rel="stylesheet" href="css/ui-button.css">
    <link rel="stylesheet" href="css/ui-form.css">
    <!--<script>
        function test(inputs) {
            inputs.forEach((v, k) => {
                if(k > 0){
                inputs[0].checked ? v.checked = true :v.checked = false
            }
        });
        }
    </script>
    -->

</head>
<body>
<!-- En-tête commune de l'application -->
<header class="blog-header">
    <h1><a href="index.php"><i class="fa fa-microphone"></i> Encore un Blog ?! #nonMaisAllo</a></h1>
    <nav>
        <a href="admin.php"><i class="fa fa-cogs"></i> Administration</a>
    </nav>
</header>







<main>


    <!-- Chargement du template PHTML spécifié par le programme PHP -->
    <!-- Page d'ajout d'un article -->
    <h2><i class="fa fa-pencil"></i> Rédiger un nouvel article</h2>

    <!-- Formulaire de saisie d'un nouvel article -->
    <form class="generic-form" action="add_post.php" method="post">


        <fieldset>
            <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
            <ul>
                <li>
                    <label for="title">Titre :</label>
                    <input type="text" id="title" name="title">
                </li>
                <li>
                    <label class="textarea" for="contents">Article :</label>
                    <textarea id="contents" name="contents" rows="15"></textarea>
                </li>
                <li>
                    <label for="author">Auteur :</label>
                    <select id="author" name="author">
                <?php
                foreach ($articleAuthorFetch as $articleAuthor)
                {
                ?>


                        <option value="<?= $articleAuthor['id_autor'] ?>"> <?= $articleAuthor['id_name'],' ', $articleAuthor['id_lastName'] ?> </option>


                <?php
                }
                ?>
                    </select>
                </li>
                <li>
                    <label for="category">Catégorie :</label>
                    <select id="category" name="category">

                <?php
                foreach ($articleCategoriesFetch as $articleCategorie)
                {
                ?>


                        <option value="<?= $articleCategorie['id_cat'] ?>"> <?= $articleCategorie['name'] ?> </option>

                    <?php
                }
                ?>
                    </select>
                </li>

                <li>
                    <button class="button button-primary" type="submit">Enregistrer</button>
                    <a class="button button-cancel" href="index.php">Annuler</a>
                </li>
            </ul>
        </fieldset>
    </form>    </main>

<!-- Pied de page commun de l'application -->
<footer class="blog-footer">
    <small>Le blog des élèves de la 3W Academy</small>
</footer>
</body>
</html>