<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Encore un Blog ?! #nonMaisAllo</title>

    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/blog-main.css">
    <link rel="stylesheet" href="css/blog-theme.css">
    <link rel="stylesheet" href="css/ui-button.css">
    <link rel="stylesheet" href="css/ui-form.css">

</head>
<body>
<!-- En-tête commune de l'application -->
<header class="blog-header">
    <h1><a href="index.php"><i class="fa fa-microphone"></i> Encore un Blog ?! #nonMaisAllo</a></h1>
    <nav>
        <a href="admin.php"><i class="fa fa-cogs"></i> Administration</a>
    </nav>
</header>

<main>
    <!-- Chargement du template PHTML spécifié par le programme PHP -->
    <h2><i class="fa fa-cogs"></i> Panneau d'administration</h2>
    <h2 style="float: right"><a href="logout.php">Deconnexion</a></h2>
    <nav>
        <a href="add_post.php">Rédiger un nouvel article</a>
    </nav>

    <table>
        <caption>Liste des articles</caption>
        <thead>
        <tr>
            <th>Titre</th>
            <th>Article</th>
            <th>Auteur</th>
            <th>Catégorie</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        Tout cocher: <input type="checkbox" onclick="test(document.querySelectorAll('input'));"><br>
        <form method="post" action="delete_post.php">




            <?php
            while ($editResult = $editReq->fetch())
            {
            ?>

            <tr>
                <td><a href="show_post.php?id=<?= $editResult['id_art'] ?>" target="_blank"><?= $editResult['title'] ?> </a></td>
                <td><?= $editResult['content'] ?></td>
                <td><?= $editResult['id_name'],' ',$editResult['id_lastName'] ?></td>
                <td><?= $editResult['name'] ?></td>

                <td>
                    <a class="edit" href="edit_post.php?id=<?= $editResult['id_art'] ?>"><i class="fa fa-pencil"></i></a>
                    <input type="checkbox" name="articles[]" value="">
                </td>
            </tr>

            <?php
            }
            ?>

            <button type="submit">supprimer</button>
        </form>
        </tbody>
    </table>    </main>

<!-- Pied de page commun de l'application -->
<footer class="blog-footer">
    <small>Le blog des élèves de la 3W Academy</small>
</footer>
</body>
</html>