
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Encore un Blog ?! #nonMaisAllo</title>

    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/blog-main.css">
    <link rel="stylesheet" href="css/blog-theme.css">
    <link rel="stylesheet" href="css/ui-button.css">
    <link rel="stylesheet" href="css/ui-form.css">

</head>
<body>
<!-- En-tête commune de l'application -->
<header class="blog-header">
    <h1><a href="index.php"><i class="fa fa-microphone"></i> Encore un Blog ?! #nonMaisAllo</a></h1>
    <nav>
        <a href="admin.php"><i class="fa fa-cogs"></i> Administration</a>
    </nav>
</header>

<main>
    <!-- Chargement du template PHTML spécifié par le programme PHP -->
    <!-- Page d'édition d'un article -->
    <h2><i class="fa fa-pencil"></i> Editer un article</h2>

    <!-- Formulaire de mise à jour d'un article -->
    <form class="generic-form" action="edit_post.php" method="post">

        <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le commentaire -->


        <fieldset>
            <legend><i class="fa fa-sticky-note-o"></i> Article</legend>
            <ul>

                <?php
                $id = $_GET['id'] ?? $_POST['gku'];
                $editArticle= $pdo->prepare
                ('SELECT * FROM `table_article` WHERE `id_art` = ?');
                $editArticle->execute(array($id));

                $editArticles = $editArticle->fetchAll();
                forEach ($editArticles as $majArticle){

                ?>


                <li>
                    <label for="title">Titre :</label>

                    <input type="text" id="title" name="title" value=" <?= $majArticle['title'] ?>">
                </li>
                <li>
                    <label class="textarea" for="contents">Article :</label>
                    <textarea id="contents" name="contents" rows="15"><?= $majArticle['content'] ?></textarea>
                </li>
                <li>
                    <input type="hidden" name="gku" value="<?= $id ?>">
                    <button class="button button-primary" type="submit">Mettre à jour</button>
                    <a class="button button-cancel" href="index.php">Annuler</a>
                </li>

                <?php
                }
                ?>

            </ul>
        </fieldset>
    </form>    </main>

<!-- Pied de page commun de l'application -->
<footer class="blog-footer">
    <small>Le blog des élèves de la 3W Academy</small>
</footer>
</body>
</html>
